### PR TITLE
Adding unit cases 202301260006

### PR DESCRIPTION
**Pull request by iskren-yordanov**
Adding all Unit cases for Collection.

Please review and comment

### CODE REVIEW

**Comment by NVelkova** [comment]
LGTM.

**Review by RositsaMiteva — APPROVED** [review]

**Comment by DamianTocev** [comment]
LGTM

**Review by NVelkova — COMMENTED** [review]
LGTM

**Comment by DamianTocev** [comment]
LGTM

**Comment by iskren-yordanov** [comment]
Merging 20230129 after review

**Pull request merged**
